/*
 ============================================================================
 Name        : Ultra_sonic.h
 Author      : MOHAMED MOSTAFA
 Description : Header file for UltraSonic Driver
 Date        : 21/10/2023
 ============================================================================
 */

#ifndef ULTRA_SONIC_H_
#define ULTRA_SONIC_H_

#include "STD_TYPES.h"
/*
 * Description :
   1- Initialize the ICU driver as required.
   2- Setup the ICU call back function.
   3- Setup the direction for the trigger pin as output pin through the GPIO driver.
 */
void Ultrasonic_init(void);


/*
 * Description :
   1- Send the Trigger pulse to the UltraSonic.
 */
void Ultrasonic_Trigger(void);


/*
 * Description :
   1- Send the trigger pulse by using Ultrasonic_Trigger function.
   2- Start the measurements by the ICU from this moment.
 */
u16 Ultrasonic_readDistance(void);


/*
 * Description :
   1- This is the call back function called by the ICU driver.
   2- This is used to calculate the high time (pulse time) generated by the UltraSonic sensor.
 */
void Ultrasonic_edgeProcessing(void);



#endif /* ULTRA_SONIC_H_ */
